### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mr-c** [bioinfomaticsCSU/EPGA#2]
What license is this code released under?

**Comment by junghans** [comment]
Due to this issue we had to drop EPGA from Gentoo's science overlay (gentoo-science/sci@3d9fc0c1f746a6eb71159b39988a8fd09d4db0c7)

**Comment by bioinfomaticsCSU** [comment]
See license in README.MD

**Comment by mr-c** [comment]
Great, thanks!
